blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('cat/<str:category>/', views.index, name='index-specific-cat'),
    path('author/<str:author_first_name>-<str:author_last_name>/', views.author_index, name='specific-author'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('edit/', views.new_post, name='new-post'),
    path('edit/<str:Id>/', views.post_editor, name='post-edit'),
    path('delete/<str:Id>/', views.delete_post, name='delete-post'),
    path('image/upload', views.post_image_upload, name='add-image'),
    path('image/delete', views.delete_image, name='delete-image'),
]

myPersonalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-home'),
    path('', include('blog.urls'), name='blog-home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
import os
import math
from hashlib import sha1
from django.utils.html import mark_safe
from django.apps import apps
from modules.index import Document, Parser

STATUS = (
	(0, "Draft"),
	(1, "Published")
	)

class PostCategory(models.Model):
	categories = models.CharField(max_length=20)

	def __str__(self):
		return self.categories

class Image(models.Model):

	def image_dir(self, filename):
		# process the file and return the path where it will be saved
		image = self.image.open()
		content = image.read()
		sha1_hash = sha1(content)
		ext = filename.split('.')[1]
		hash = sha1_hash.hexdigest()
		return f'{hash[0:2]}/{hash[2:]}.{ext}'

	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_images')
	original_name = models.CharField(max_length=200)
	image = models.ImageField(upload_to=image_dir)
	post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='post_images', blank=True, null=True)

	@property
	def image_preview(self):
		if self.image:
			return mark_safe('<img src="{0}" width="{1}" height="{2}" />'.format(self.image.url, min(500, self.image.width), min(500, self.image.height)))
		return ""

	def __str__(self):
		return self.original_name

class Post(models.Model):

	class Meta:
		ordering = ['-created_on']

	def image_dir(self, filename):
		image = self.title_image.open()
		content = image.read()
		sha1_hash = sha1(content)
		ext = filename.split('.')[1]
		return f'{sha1_hash.hexdigest()[0:2]}/{sha1_hash.hexdigest()[2:]}.{ext}'

	title = models.CharField(max_length=200)
	category = models.ForeignKey(PostCategory, on_delete=models.SET_NULL, related_name='posts', blank=True, null=True)
	slug = models.SlugField(default='', editable=False)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	created_on = models.DateField(auto_now_add=True)
	updated_on = models.DateField(auto_now=True)
	content = models.TextField()
	first_paragraph = models.TextField()
	status = models.IntegerField(choices=STATUS, default=0)
	title_image = models.ForeignKey(Image, on_delete=models.SET_NULL, related_name='blogs', blank=True, null=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super().save(*args, **kwargs)
		# update index
		doc = Document(self.pk, self.content, self.title, self.author.first_name, self.author.last_name)
		index = apps.get_app_config('blog').index
		if self.pk is not None:
			index.remove(doc)
		index.add(doc)
		index.save()

	def delete(self, *args, **kwargs):
		# remove document from index
		doc = Document(self.pk, self.content, self.title, self.author.first_name, self.author.last_name)
		index = apps.get_app_config('blog').index
		index.remove(doc)
		index.save()
		# delete from database
		super().delete(*args, **kwargs)

	@property
	def title_image_preview(self):
		if self.title_image:
			return mark_safe('<img src="{0}" width="{1}" height="{2}" />'.format(self.title_image.url, min(500, self.title_image.width), min(500, self.title_image.height)))
		return ""

	def __str__(self):
		return self.title

	def get_relevance_score(self, search):
		score = 0
		parser = Parser()
		doc = Document(self.pk, self.content, self.title, self.author.first_name, self.author.last_name)
		search_tokens = parser.parse(search, stem=False)
		for search_token in search_tokens:
			for field in doc.fields:
				field = field.lower()
				if search_token in field:
					term_freq = math.sqrt(field.count(search_token))
					norm = 1 / math.sqrt(len(parser.parse(field)))
					score += term_freq * norm
		return score

	
class UserProfile(models.Model):

	def image_dir(self, filename):
		image = self.avatar.open()
		content = image.read()
		sha1_hash = sha1(content)
		ext = filename.split('.')[1]
		return f'{sha1_hash.hexdigest()[0:2]}/{sha1_hash.hexdigest()[2:]}.{ext}'

	@property
	def avatar_preview(self):
		if self.avatar:
			return mark_safe('<img src="{0}" width="{1}" height="{2}" />'.format(self.avatar.url, min(500, self.avatar.width), min(500, self.avatar.height)))
		return ""

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to=image_dir, blank=True, max_length=255)

blog/views.py
from django.contrib.auth.decorators import login_required
from django import template
from django.http import HttpResponse
from django.template import loader
import markdown
import bleach
import json
from bs4 import BeautifulSoup
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.apps import apps
from myPersonalSite.settings import ALLOWED_HTML_TAGS, ALLOWED_HTML_ATTRS


def chunks(iterator, n):
	for i in range(0, len(iterator), n):
		yield iterator[i:i + n]


from .models import Post, User, PostCategory, Image

def post_detail(request, slug):

	template = loader.get_template('blog/post.html')
	md = markdown.Markdown(extensions=['markdown.extensions.fenced_code', 'markdown.extensions.tables', 'extra'])

	if request.method == 'POST':
		header_image_id = request.POST.get('header-image-id')
		if header_image_id != "-1":
			image = Image.objects.get(id=header_image_id)
		else:
			image = None
		try:
			post = Post.objects.get(id=request.POST.get('post-id'))
			post.content = bleach.clean(request.POST.get('markdown'), tags=ALLOWED_HTML_TAGS, attributes=ALLOWED_HTML_ATTRS)
			post.first_paragraph = BeautifulSoup(md.convert(bleach.clean(post.content)), features="html.parser").find('p').text
			post.title = request.POST.get('title')
			post.author = User.objects.get(id=request.POST.get('user'))
			post.status = request.POST.get('status')
			post.category = PostCategory.objects.get(id=request.POST.get('category'))
			header_image_id = request.POST.get('header-image-id')
			post.title_image = image
		except Post.DoesNotExist:
			content = bleach.clean(request.POST.get('markdown'), tags=ALLOWED_HTML_TAGS, attributes=ALLOWED_HTML_ATTRS)
			post = Post(
				content = content, 
				first_paragraph = BeautifulSoup(md.convert(bleach.clean(content)), features="html.parser").find('p').text,
				title = request.POST.get('title', ''), 
				author = User.objects.get(id=request.POST.get('user')), 
				status = request.POST.get('status'),
				title_image = image,
				category = PostCategory.objects.get(id=request.POST.get('category'))
				)
		post.save()
		images = Image.objects.filter(post__isnull=True)
		for img in images:
			img.post = post
			img.save()
	
	post = get_object_or_404(Post, slug=slug)
	# convert markdown to html server-side
	post.content = md.convert(post.content)
	categories = PostCategory.objects.all()
	user_profile = post.author.userprofile
	context = {'post': post, 'user_profile': user_profile, 'categories': categories}
	return HttpResponse(template.render(context, request))

def index(request, category='All'):
	template = loader.get_template('blog/index.html')

	query = request.GET.get('q')
	if query:
		index = apps.get_app_config('blog').index
		results = index.search(query)
		unsorted_posts = Post.objects.filter(status=1, id__in=tuple(results)).all()
		posts = sorted(unsorted_posts, key=lambda p: p.get_relevance_score(query), reverse=True)
	elif category == 'All':
		posts = Post.objects.filter(status=1)
	elif category == 'Drafts':
		posts = Post.objects.filter(status=0)
	else:
		posts = Post.objects.filter(status=1, category__categories__contains=category)

	paginator = Paginator(posts, 6)
	page_number = request.GET.get('page', 1)
	page_posts = paginator.get_page(page_number)
	categories = PostCategory.objects.all()
	if query:
		context = {'posts': page_posts, 'categories': categories, 'category': category, 'query': query}
	else:
		context = {'posts': page_posts, 'categories': categories, 'category': category}
	return HttpResponse(template.render(context, request))

def author_index(request, author_first_name, author_last_name):
	posts = Post.objects.filter(status=1, author__first_name__contains=author_first_name, author__last_name__contains=author_last_name)
	paginator = Paginator(posts, 8)
	page_number = request.GET.get('page', 1)
	page_posts = paginator.get_page(page_number)
	categories = PostCategory.objects.all()
	template = loader.get_template('blog/index.html')
	context = {'posts': page_posts, 'categories': categories, 'category': 'All'}
	return HttpResponse(template.render(context, request))

def _get_edit_context(post, include_images=False):
	users = User.objects.all()
	categories = PostCategory.objects.all()
	user_profile = post.author.userprofile
	if include_images:
		post_images = Image.objects.filter(post=post.id)
		post_image_chunks = list(chunks(post_images, 3))
		return {'post': post, 'user_profile': user_profile, 'users': users, 'categories': categories, 'image_chunks': post_image_chunks}
	return {'post': post, 'user_profile': user_profile, 'users': users, 'categories': categories}

@login_required
def post_editor(request, Id):
	template = loader.get_template('blog/post-editor.html')
	post = get_object_or_404(Post, id=Id)
	context = _get_edit_context(post, include_images=True)
	return HttpResponse(template.render(context, request))

@login_required
def new_post(request):
	template = loader.get_template('blog/post-editor.html')
	post = Post(title="", author=request.user, content="", slug="new")
	context = _get_edit_context(post, include_images=True)
	return HttpResponse(template.render(context, request))

@login_required
def post_image_upload(request):
	image = request.FILES.get('image')
	user = User.objects.get(id=request.POST.get('user', ''))
	try:
		post = Post.objects.get(id=request.POST.get('post_id'))
		post_image = Image(user=user, original_name=image.name, image=image, post=post)
	# If the post's id is 'None', it means this is a new post.
	except ValueError:
		# The post image's post field is null for now but it will be updated one the new post is
		# saved. If the post isn't saved, image garbage collection will delete the image.
		post_image = Image(user=user, original_name=image.name, image=image)
	post_image.save()
	data = json.dumps({'image': {'url': post_image.image.url, 'id': post_image.id}})
	return HttpResponse(data, content_type='application/json')

@login_required
def delete_image(request):
	image_id = request.POST.get('image_id')
	image = Image.objects.get(id=image_id)
	deleted_image_data = json.dumps({'image_id': image_id})
	image.delete()
	return HttpResponse(deleted_image_data, content_type='application/json')

@login_required
def delete_post(request, Id):
	template = loader.get_template('blog/post-delete.html')
	post = get_object_or_404(Post, id=Id)
	post.delete()
	context = {'post': post}
	return HttpResponse(template.render(context, request))

blog/templates/blog/base.html
<!DOCTYPE html>
<html>

    <head>
        {% load static %}
        {% block head %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}">
        {% endblock %}
        {% block title %}
        <title>Joe Writes Stuff</title>
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro|Roboto+Slab" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
    </head>

    <body>

        <!--Navbar blue-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog:index' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:index-specific-cat' 'Drafts' %}">Drafts</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:new-post' %}">New Post</a>
                    </li>
                    {% endif %}
                    {% if categories %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'blog:index' %}">All</a>
                            {% for cat in categories %}
                            <a class="dropdown-item" href="{% url 'blog:index-specific-cat' cat %}">{{ cat }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    {% endif %}
                </ul>
                <form class="form-inline" action="{% url 'blog:index' %}">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q">
                </form>
            </div>
        </nav>

        {% block body %}{% endblock %}

    </body>

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block body %}
  {% if query %}
  <div style="margin-top: 5px;"><h4>Results for: "{{ query }}"</h4></div>
  {% endif %}
  {% if posts %}
  <ul class="cards">
  {% for post in posts %}
  <li class="cards__item">
    <div class="card">
      {% if post.title_image %}
      <img class="card-img-top" src="{{ post.title_image.image.url }}"/>
      {% else %}
      <div class="card-img-top" style="background-color: rgb(24, 37, 52);"></div>
      {% endif %}
      <div class="card-img-overlay">
        <a href="{% url 'blog:index-specific-cat' post.category %}" class="btn btn-light btn-sm">{{ post.category }}</a>
      </div>
      <div class="author">
        <img src="{{ post.author.userprofile.avatar.url }}" alt="" class="author-image">
        <a class="author-name" href="{% url 'blog:specific-author' post.author.first_name post.author.last_name %}">{{ post.author.first_name }}</a>
      </div>
      <div class="card-body">
        <h4 class="card-title">{{ post.title }}</h4>
        <p class="card-text">{{ post.first_paragraph | slice:"0:250" }} [...]</p>
        <a href="{% url 'blog:post-detail' post.slug %}" class="btn btn-primary">Read More</a>
        <div class="sharing">
          <a id="twitter" href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-url="{{ request.build_absolute_uri|slice:":-1" }}{% url 'blog:post-detail' post.slug %}" data-show-count="false">Tweet</a>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
          <script type="IN/Share" data-url="{{ request.build_absolute_uri|slice:":-1" }}{% url 'blog:post-detail' post.slug %}"></script>
        </div>
      </div>
      <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
        <div class="views">{{ post.updated_on }}</div>
      </div>
    </li>
  {% endfor %}
  </ul>
  {% else %}
      <p style="text-align: center;">No posts are available.</p>
  {% endif %}

  <div id="pagination-container">
    <ul id="pagination">
      {% if posts.has_previous %}
        <li class="arrow"><a href="?page={{ posts.previous_page_number }}"><i class="fas fa-chevron-left"></i></a></li>
      {% else %}
        <li class="arrow"><a href="?page=1"><i class="fas fa-chevron-left"></i></a></li>
      {% endif %}
      <li>Page <a href="?page={{ posts.number }}">{{ posts.number }}</a> of <a href="?page={{ posts.paginator.num_pages }}">{{ posts.paginator.num_pages }}</a></li>
      {% if posts.has_next %}
        <li class="arrow"><a href="?page={{ posts.next_page_number }}"><i class="fas fa-chevron-right"></i></a></li>
      {% else %}
        <li class="arrow"><a href="?page={{ posts.number }}"><i class="fas fa-chevron-right"></i></a></li>
      {% endif %}
    </ul>
  </div>
{% endblock %}

blog/templates/blog/post-change.html
{% extends "blog/post.html" %}

{% block post_styling %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-change-style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
{% endblock %}

{% block title %}
<input id="title" form="save-changes" value="{{ post.title }}" name="title"></input>
{% endblock %}

{% block post_content %}
<div id="edit-toolbar">
  <form id="save-changes" action="{% url 'post-detail' post.slug %}" method="post">
    {% csrf_token %}
    <button id="edit" type="submit"><i class="fas fa-share-square"></i></button>
  </form>
</div>
<div class="flex-container-content">
  <div id="markdown-editor-container"><textarea spellcheck="true" id="markdown-editor" cols=120 form="save-changes" name="markdown">{{ post.content }}"</textarea></div>
  <div id="content"></div>
</div>

<script>
  let markdown_elem = document.getElementById('markdown-editor');
  document.getElementById('content').innerHTML = marked(markdown_elem.value);
  markdown_elem.addEventListener("input", (event) => {
    document.getElementById('content').innerHTML = marked(markdown_elem.value);
  });
</script>
{% endblock %}

blog/templates/blog/post-delete.html
{% extends "blog/base.html" %}

{% block body %}
<p style="margin-top: 50px;">"{{ post.title }}" was successfully deleted.</p>
{% endblock %}

blog/templates/blog/post-editor.html
{% extends "blog/post.html" %}

{% block head %}
{% load static %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/post.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-editor.css' %}">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
  const UPLOAD_IMAGE_ENDPOINT = "{% url 'blog:add-image' %}";
  const DELETE_IMAGE_ENDPOINT = "{% url 'blog:delete-image' %}";
  const USER_ID = "{{ request.user.id }}";
  const POST_ID = "{{ post.id }}";
</script>
<script src="{% static 'blog/post-editor.js' %}" defer></script>
{% endblock %}

{% block post_title %}
<div>
  <!-- add a header image button -->
  <button id="add-header-image" class="toolbar-item" type="button" title="add header image">
    <i class="fas fa-image"></i>
  </button>
  <input style="display: none;" id="add-header-image-input" type="file" accept="image/*" name="header-image" onchange="uploadImage(this, addImageToHeader)">
  <!-- this stores the header's image id when a new image is uploaded via the fetch API -->
  <input style="display: none;" id="header-image-id" type="number" form="save-changes" name="header-image-id" {% if post.title_image is not None %}value={{ post.title_image.id }}{% else %}value="-1"{% endif %}></input>
</div>
<input id="title" form="save-changes" value="{{ post.title }}" name="title" oninput="updateSaveAction()" required></input>
{% endblock %}
<!-- we don't want to include social media sharing buttons while editing -->
{% block sharing %}{% endblock %}

{% block user_select %}
<div class="selector">
  <label for="user">Post Author:</label>
  <select name="user" id="user" form="save-changes">
    {% for user in users %}
    <option value="{{ user.id }}" {% if post.author == user %}selected="selected"{% endif %}>{{ user.username }}</option>
    {% endfor %}
  </select>
</div>
{% endblock %}

{% block post_content %}
<div id="selectors-container">
  <!-- selector for the post's status -->
  <div class="selector">
    <label for="status">Post Status:</label>
    <select name="status" id="status" class="toolbar-item" form="save-changes">
      <option value="0" {% if post.status == None or post.status == 0 %}selected="selected"{% endif %}>Draft</option>
      <option value="1" {% if post.status == 1 %}selected="selected"{% endif %}>Publish</option>
    </select>
  </div>
  <!-- selector for the post's category -->
  <div class="selector">
    <label for="category">Post Category:</label>
    <select name="category" id="category" class="toolbar-item" form="save-changes" required>
      {% if post.category == None %}<option label=" " style="display: none;" selected="selected"></option>{% endif %}
      {% for cat in categories %}
      <option value="{{ cat.id }}" {% if post.category == cat %}selected="selected"{% endif %}>{{ cat }}</option>
      {% endfor %}
    </select>
  </div>
</div>
<div id="edit-toolbar">
  <!-- save changes form -->
  <form id="save-changes" action="{% url 'blog:post-detail' post.slug %}" method="post">
    {% csrf_token %}
    <input type="hidden" {% if post.id %}value="{{ post.id }}"{% else %}value="-1"{% endif %} name="post-id" id="post-id">
    <button id="save" class="toolbar-item" type="submit" title="save changes"><i class="fas fa-share-square"></i></button>
  </form>
  {% if post.id %}
  <!-- delete post form -->
  <form onsubmit="return confirm('Are you sure you want to delete this post?');" action="{% url 'blog:delete-post' post.id %}">
    <button id="delete" class="toolbar-item" type="submit" title="delete post"><i class="fas fa-trash-alt"></i></button>
  </form>
  {% endif %}
  <!-- add image to post button -->
  <button id="add-image-button" class="toolbar-item" type="button" title="add image to post"><i class="fas fa-image"></i></button>
  <input style="display: none;" id="add-image-input" class="toolbar-item" type="file" accept="image/*" name="image" onchange="uploadImage(this, addImageToPost)">
  <!-- view and edit post images uploaded -->
  <button type="button" class="toolbar-item" data-toggle="modal" data-target="#post-images-form" title="view and edit uploaded images"><i class="fas fa-images"></i></button>
  <!-- add quote button. displays a form -->
  <button type="button" class="toolbar-item" data-toggle="modal" data-target="#quote-form" title="add quote to post"><i class="fas fa-quote-left"></i></button>
</div>
<div class="flex-container-content">
  <div id="markdown-editor-container"><textarea spellcheck="true" id="markdown-editor" cols=120 form="save-changes" name="markdown">{{ post.content }}</textarea></div>
  <div id="content"></div>
</div>
{% endblock %}

{% block additions %}
<!-- add quote Bootstrap Modal -->
<div class="modal fade" id="quote-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <h5 class="modal-title" id="exampleModalLabel">Add Blockquote to Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form class="form-container">
        <div class="modal-body">
          <div class="form-group">
            <label for="quote">Quote</label>
            <textarea id="quote" class="form-control form-control-sm mb-3" rows="3" placeholder="Enter quote"></textarea>
          </div>
          <div class="form-group">
            <label for="citation">Citation</label>
            <input type="text" class="form-control" id="citation" placeholder="Citation">
          </div>
          <div class="form-group">
            <label for="citation-url">Link to Source</label>
            <input type="url" class="form-control" id="citation-url" placeholder="url">
          </div>
        </div>
        <div class="modal-footer border-top-0 d-flex justify-content-center">
          <button type="button" class="btn btn-success" onclick="addQuote()">Add Quote</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- post images Bootstrap Modal -->
<div class="modal fade" id="post-images-form" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Uploaded Post Images</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div id="images-container">
            {% if image_chunks %}
              {% for chunk in image_chunks %}
                <div class="row" {% if forloop.last %}id="last-row"{% else %}id="row-{{ forloop.counter }}"{% endif %}>
                  {% for image in chunk %}
                    <div class="image-container" id="image-container-{{ image.id }}">
                        <img class="img-fluid rounded" src='{{ image.image.url }}'>
                        <a class="remove-image" id="{{ image.id }}"><i class="fas fa-trash-alt"></i></a>
                        <!-- copy the images url to the clipboard -->
                        <input type="text" value="{{ image.image.url }}" id="url-{{ image.id }}" style="display: none;">
                        <div class="mytooltip" id="tooltip-{{ image.id }}">
                          <button class="toolbar-item" onclick="copyUrl('url-{{ image.id }}', 'tooltip-{{ image.id }}-text')" onmouseout="outFunc('tooltip-{{ image.id }}-text')">
                            <span class="tooltiptext" id="tooltip-{{ image.id }}-text">Copy to clipboard</span>
                            <i class="fas fa-link"></i>
                          </button>
                        </div>
                    </div>
                  {% endfor %}
                </div>
              {% endfor %}
            {% else %}
              <div class="row" id="last-row"></div>
            {% endif %}
              <button id="add-image-to-modal-button"><i class="fas fa-plus"></i></button>
              <input style="display: none;" id="add-image-to-modal-input" class="toolbar-item" type="file" accept="image/*" name="image" onchange="uploadImage(this, addImageToUploadedModal)">
          </div>
      </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}